
package superlines.ws.artefacts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SuperlinesWebservice", targetNamespace = "http://ws.server.superlines/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SuperlinesWebservice {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorize", targetNamespace = "http://ws.server.superlines/", className = "superlines.ws.artefacts.Authorize")
    @ResponseWrapper(localName = "authorizeResponse", targetNamespace = "http://ws.server.superlines/", className = "superlines.ws.artefacts.AuthorizeResponse")
    @Action(input = "http://ws.server.superlines/SuperlinesWebservice/authorizeRequest", output = "http://ws.server.superlines/SuperlinesWebservice/authorizeResponse")
    public boolean authorize(
        @WebParam(name = "arg0", targetNamespace = "")
        InvocationContext arg0);

}
