/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package superlines.client.ui;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JFrame;
import javax.swing.JPanel;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import superlines.client.SuperlinesController;
import superlines.client.SuperlinesControllerImpl;

/**
 *
 * @author Sashonk
 */
public class MainFrame extends javax.swing.JFrame {
	
	private final static Log log = LogFactory.getLog(MainFrame.class);

    private static MainFrame instance ;
    /**
     * Creates new form MainFrame
     */
     MainFrame() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        setLocation(x, y); 
       setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       
       this.addWindowListener(new WindowAdapter() {
				@Override
				public void windowClosing(WindowEvent evt) {
				log.debug("application terminate");
				System.exit(0);
				}
		});

  
    }
    
    
    public static MainFrame get(){
        if(instance==null){
            instance = new MainFrame();
        }
        
        return instance;
    }
    
    
    public void showScorePanel(){
        showPanel(ScorePanel.class);
    }
     public void showPlayPanel(){
        showPanel(PlayPanel.class);
    }   

    
    void showPanel(Class<? extends JPanel> cls){
        for(Component c : getContentPane().getComponents()){
            if(c.getClass()==cls){
                c.setVisible(true);                
            }
            else{
                c.setVisible(false);
            }
        }
        
    }
    
    void shutdown(){
        System.exit(0);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
