/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package superlines.client.ui;

import superlines.core.SuperlinesController;
import superlines.core.SuperlinesListener;

/**
 *
 * @author Sashonk
 */
public class PlayPanel extends javax.swing.JPanel implements SuperlinesListener{

	private SuperlinesController m_controller;
    /**
     * Creates new form PlayPanel
     */
    public PlayPanel(final SuperlinesController ctr) {
        initComponents();
        
        m_controller= ctr;
        
        SuperlinesPanel sp = (SuperlinesPanel)superlinesPanel;
        sp.test();
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        playerNameField = new javax.swing.JTextField();
        scoreLabel = new javax.swing.JLabel();
        scoreField = new javax.swing.JTextField();
        maxScoreLabel = new javax.swing.JLabel();
        maxScoreField = new javax.swing.JTextField();
        middlePanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        superlinesPanel = new SuperlinesPanel();
        rightPanel = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();
        toScoreBtn = new javax.swing.JButton();
        scatterButton = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        topPanel.setBackground(new java.awt.Color(255, 204, 204));
        topPanel.setMaximumSize(new java.awt.Dimension(32767, 80));
        topPanel.setName(""); // NOI18N
        topPanel.setPreferredSize(new java.awt.Dimension(495, 60));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        topPanel.setLayout(flowLayout1);

        playerNameField.setEditable(false);
        playerNameField.setText("player");
        playerNameField.setToolTipText("player name");
        topPanel.add(playerNameField);

        scoreLabel.setText("jLabel1");
        topPanel.add(scoreLabel);

        scoreField.setEditable(false);
        scoreField.setText("1111");
        topPanel.add(scoreField);

        maxScoreLabel.setText("jLabel2");
        topPanel.add(maxScoreLabel);

        maxScoreField.setEditable(false);
        maxScoreField.setText("12000");
        topPanel.add(maxScoreField);

        add(topPanel);

        middlePanel.setBackground(new java.awt.Color(204, 255, 204));
        middlePanel.setLayout(new javax.swing.BoxLayout(middlePanel, javax.swing.BoxLayout.LINE_AXIS));

        leftPanel.setPreferredSize(new java.awt.Dimension(50, 200));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        middlePanel.add(leftPanel);

        superlinesPanel.setBackground(new java.awt.Color(153, 153, 153));
        superlinesPanel.setPreferredSize(null);
        superlinesPanel.setLayout(new java.awt.GridBagLayout());
        middlePanel.add(superlinesPanel);

        rightPanel.setPreferredSize(new java.awt.Dimension(50, 244));

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        middlePanel.add(rightPanel);

        add(middlePanel);

        bottomPanel.setBackground(new java.awt.Color(204, 204, 255));
        bottomPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        bottomPanel.setPreferredSize(new java.awt.Dimension(495, 80));

        toScoreBtn.setText("toScore");
        toScoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toScoreBtnActionPerformed(evt);
            }
        });
        bottomPanel.add(toScoreBtn);

        scatterButton.setText("scatter");
        scatterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scatterButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(scatterButton);

        add(bottomPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void scatterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scatterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scatterButtonActionPerformed

    private void toScoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toScoreBtnActionPerformed
        MainFrame.get().showScorePanel();        // TODO add your handling code here:
    }//GEN-LAST:event_toScoreBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JTextField maxScoreField;
    private javax.swing.JLabel maxScoreLabel;
    private javax.swing.JPanel middlePanel;
    private javax.swing.JTextField playerNameField;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton scatterButton;
    private javax.swing.JTextField scoreField;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JPanel superlinesPanel;
    private javax.swing.JButton toScoreBtn;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
